name: Django CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: github_actions
                ports:
                    - 5433:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8, 3.9, '3.10']

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run Tests
              env:
                  DEBUG: ${{ secrets.DEBUG }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  PSQL_DB_NAME: ${{ secrets.PSQL_DB_NAME }}
                  PSQL_DB_USER: ${{ secrets.PSQL_DB_USER }}
                  PSQL_DB_USER_PWD: ${{ secrets.PSQL_DB_USER_PWD }}
                  PSQL_DB_HOST: ${{ secrets.PSQL_DB_HOST }}
                  PSQL_DB_PORT: ${{ secrets.PSQL_DB_PORT }}
                  GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
              run: |
                  python manage.py collectstatic --no-input
                  coverage run manage.py test && coverage report --fail-under=80 && coverage xml

            - name: Report coverage to Codecov
              env:
                  DEBUG: ${{ secrets.DEBUG }}
                  SECRET_KEY: ${{ secrets.SECRET_KEY }}
                  PSQL_DB_NAME: ${{ secrets.PSQL_DB_NAME }}
                  PSQL_DB_USER: ${{ secrets.PSQL_DB_USER }}
                  PSQL_DB_USER_PWD: ${{ secrets.PSQL_DB_USER_PWD }}
                  PSQL_DB_HOST: ${{ secrets.PSQL_DB_HOST }}
                  PSQL_DB_PORT: ${{ secrets.PSQL_DB_PORT }}
                  GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
              uses: codecov/codecov-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
                  directory: ./coverage/reports/
                  fail_ci_if_error: true
